import { createRoot } from 'react-dom/client'
import '@fontsource/unbounded/cyrillic-300.css'
import '@fontsource/unbounded/latin-300.css'
import '@fontsource/unbounded/cyrillic-500.css'
import '@fontsource/unbounded/latin-500.css'
import '@fontsource/ibm-plex-sans/cyrillic-300.css'
import '@fontsource/ibm-plex-sans/latin-300.css'
import '@fontsource/ibm-plex-sans/cyrillic-300-italic.css'
import '@fontsource/ibm-plex-sans/latin-300-italic.css'
import '@fontsource/ibm-plex-mono/cyrillic-400.css'
import '@fontsource/ibm-plex-mono/latin-400.css'
import './styles.css'
import { App } from './App'
import './debug'

createRoot(document.getElementById('root')!).render(<App />)
